---
name: Coupon API - Test Regresion
"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instal Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --cov=app --cov-report html tests/

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
